# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  #Creating Proxy Server
  config.vm.define "proxy" do |proxy|
    proxy.vm.box = 'centos/7'
    proxy.vm.network :private_network, ip:"10.120.0.2", netmask:"255.255.255.0"
    proxy.vm.hostname = "proxy.vagrant.local"
    proxy.cache.scope = :box

   #Inline Shell Provision
   proxy.vm.provision "shell",
    inline: "sudo yum update; sudo yum install nginx; sudo systemctl start nginx"

    #Configuring Memory and CPUS
    proxy.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 2
    end
  end

  #Creating Wordpress Server
  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.box = 'centos/7'
    wordpress.vm.network :private_network, ip:"10.120.0.3", netmask:"255.255.255.0"
    wordpress.vm.hostname = "wordpress.vagrant.local"
    wordpress.cache.scope = :box

  #Inline Shell Provisioning
  wordpress.vm.provision "shell",
    inline: "sudo yum update"

    #Configuring Memory and CPUS
    wordpress.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 2
    end
  end

  #Creating DB Server
  config.vm.define "db" do |db|
    db.vm.box = 'centos/7'
    db.vm.network :private_network, ip:"10.120.0.4", netmask:"255.255.255.0"
    db.vm.hostname = "db.vagrant.local"
    db.cache.scope = :box

    #Inline Shell Provisioning
    db.vm.provision "shell",
      inline: "sudo yum update"

    #Configuring Memory and CPUS
    db.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 2
    end
  end

end