# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #if Vagrant.has_plugin?("vagrant-cachier")
  #config.cache.scope       = :machine # or :box
  #config.cache.auto_detect = false
  config.vm.box = 'centos/7'
  config.vm.network :private_network, ip:"10.120.0.2", netmask:"255.255.255.0"
  config.vm.hostname = "proxy.vagrant.local"

  #Configuring Memory and CPUS
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 2
  end
end