# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
  config.vm.box = 'centos/7'
  #config.cache.scope       = :machine # or :box
  #config.cache.auto_detect = false
end