# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = 'centos/7'
  
  #Vagrant-Cachier
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "proxy" do |proxy|
  #Network
  config.vm.network "private_network", ip: "10.120.0.2", netmask: "255.255.255.0"
  #HostName
  config.vm.hostname = "proxy.vagrant.local"
  #CPU and Memory
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2
    config.vm.provision "shell", inline: $script
  end

  config.vm.define "wordpress" do |wordpress|
  #Network
  config.vm.network "private_network", ip: "10.120.0.3", netmask: "255.255.255.0"
  #HostName
  config.vm.hostname = "wordpress.vagrant.local"
  #CPU and Memory
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2
    config.vm.provision "shell", inline: "sudo yum -y update"
  end  
end

  config.vm.define "db" do |db|
    #Network
    config.vm.network "private_network", ip: "10.120.0.4", netmask: "255.255.255.0"
    #HostName
    config.vm.hostname = "db.vagrant.local"
    #CPU and Memory
    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 2
      config.vm.provision "shell", inline: "sudo yum -y update"
    end 
  end

  config.group.groups = {
    "frontend" => [
      "proxy",
    ],
    "backend" => [
      "wordpress",
      "db",
    ],
  }

  $script = <<-SCRIPT
  sudo yum update -y
  echo updating the system...
    sudo yum install epel-release -y
    echo installing epel-release repo...
    sudo yum install nginx -y
    echo installing nginx...
    SCRIPT

end
end