# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.network :public_network, ip:"10.120.0.2", netmask: "255.255.255.0"
  config.vm.hostname = "marc.testdomain"


  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.hostname = "wordpress.vagrant.local"
  end


  config.vm.define "db" do |db|
    db.vm.hostname = "db.vagrant.local"
  end
 
 if Vagrant.has_plugin?("vagrant-cachier")
  # do something like:  config.cache.scope = :box
  end 

   config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
    vb.memory = 512
    vb.cpus = 2
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
