# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "home" do |home|
  config.vm.box = "centos/7"
  config.vm.network :public_network, ip:"10.120.0.2", netmask: "255.255.255.0"
  config.vm.hostname = "proxy.vagrant.local"

    config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
    vb.memory = 512
    vb.cpus = 2
   end
 end
   Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "sudo apt-get update"
end

  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.hostname = "wordpress.vagrant.local"
    config.vm.network :public_network, ip:"10.120.0.3", netmask: "255.255.255.0"
    config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
    vb.memory = 512
    vb.cpus = 2
   end
      Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "sudo apt-get update"
end
  end


  config.vm.define "db" do |db|
    db.vm.hostname = "db.vagrant.local"
    config.vm.network :public_network, ip:"10.120.0.4", netmask: "255.255.255.0"
    config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
    vb.memory = 512
    vb.cpus = 2
   end
   Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "sudo apt-get update"
end
  end
 
 if Vagrant.has_plugin?("vagrant-cachier")
  # do something like:  config.cache.scope = :box
  end 


end
